language: cpp
branches:
  only:
    - master
    - testing
    - travis
matrix:
  include:
  - os: linux
    arch: amd64
    sudo: required
    dist: focal
    sudo: require
    addons:
      apt:
        sources:
        - sourceline: 'ppa:beineri/opt-qt-5.15.2-focal'
        packages:
        - qt515base
    before_install:
      - sudo apt-get update
      - sudo apt-get -y install qtbase5-dev libsqlite3-dev
      - sudo apt-get -y install libhamlib++-dev libqt5charts5-dev qt5-default qttools5-dev-tools libqt5keychain1 qt5keychain-dev
    compiler:
      - gcc
    script:
      - qmake QLog.pro
      - make
