name: CI Linux/macOS

on:
  push:
    branches:
      - 'testing_*'
  pull_request:
    branches:
      - 'testing_*'
      - master
jobs:
  ubuntu-build-qt5:
    name: Ubuntu CI QT5
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    if: false
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install dependencies
      run: |
         sudo apt-get update
         sudo apt-get -y install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools libsqlite3-dev libhamlib++-dev libqt5charts5-dev qttools5-dev-tools libqt5keychain1 qt5keychain-dev qtwebengine5-dev build-essential libqt5serialport5-dev pkg-config
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: configure
      run: qmake QLog.pro
    - name: make
      run: make -j2

  ubuntu-build-qt6:
    name: Ubuntu CI QT6
    strategy:
      matrix:
        os: [ubuntu-22.04]
    
    if: false    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install dependencies
      run: |
         sudo apt-get update
         sudo apt-get -y install libhamlib-dev build-essential pkg-config qt6-base-dev qtkeychain-qt6-dev qt6-webengine-dev libqt6charts6-dev libqt6serialport6-dev libqt6webenginecore6-bin libqt6svg6-dev libgl-dev
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: configure
      run: qmake6 QLog.pro
    - name: make
      run: make -j2

  macos-build:
     name: MacOS CI
     strategy:
       matrix:
         os: [macos-14]

     runs-on: ${{ matrix.os }}

     steps:
     - name: Install dependencies
       run: |
         unset HOMEBREW_NO_INSTALL_FROM_API
         brew update
         brew upgrade || true
         brew install qt6
         brew link qt6 --force
         brew install hamlib
         brew link hamlib --force
         brew install qtkeychain
         brew install dbus-glib
         brew install brotli
         brew install icu4c
         brew install pkg-config

     - name: Checkout code
       uses: actions/checkout@v4
       with:
         submodules: recursive
     - name: Configure and compile
       run: |
         mkdir build
         cd build
         qmake6 -config release ..
         make -j4
     - name: Build dmg
       run: |
         cd build
         macdeployqt qlog.app
         cp `brew --prefix`/lib/libhamlib.dylib qlog.app/Contents/Frameworks/libhamlib.dylib
         cp `brew --prefix`/lib/libqt6keychain.dylib qlog.app/Contents/Frameworks/libqt6keychain.dylib
         cp `brew --prefix`/lib/libdbus-1.dylib qlog.app/Contents/Frameworks/libdbus-1.dylib
         cp `brew --prefix brotli`/lib/libbrotlicommon.1.dylib qlog.app/Contents/Frameworks/libbrotlicommon.1.dylib
         cp `brew --prefix`/opt/icu4c/lib/libicui18n.73.dylib qlog.app/Contents/Frameworks/libicui18n.73.dylib
         install_name_tool -change `brew --prefix`/lib/libhamlib.dylib @executable_path/../Frameworks/libhamlib.dylib qlog.app/Contents/MacOS/qlog
         install_name_tool -change `brew --prefix`/lib/libqt6keychain.dylib @executable_path/../Frameworks/libqt6keychain.dylib qlog.app/Contents/MacOS/qlog
         install_name_tool -change @loader_path/libbrotlicommon.1.dylib @executable_path/../Frameworks/libbrotlicommon.1.dylib qlog.app/Contents/MacOS/qlog
         install_name_tool -change `brew --prefix`/opt/icu4c/lib/libicui18n.73.dylib @executable_path/../Frameworks/libicui18n.73.dylib qlog.app/Contents/MacOS/qlog
         otool -L qlog.app/Contents/MacOS/qlog
         macdeployqt qlog.app -dmg
     - name: Copy artifact
       uses: actions/upload-artifact@v3
       with:
         name: qlog
         path: /Users/runner/work/QLog/QLog/build/qlog.dmg
