name: macOS 12 deployment

#on: [push, pull_request]

on:
  workflow_dispatch:
  push:
     branches:
       - master

jobs:
  macos-build:
     name: MacOS Build
     runs-on: macos-12

     steps:
     - name: Install Dependencies
       run: |
         brew update
         brew install qt6
         brew link qt6 --force
         brew install hamlib
         brew link hamlib --force
         brew install qtkeychain
     - name: Checkout Code
       uses: actions/checkout@v3
       with:
         submodules: recursive
     - name: Configure and Compile
       run: |
         mkdir build
         cd build
         qmake -config release ..
         make -j2
     - name: Build dmg
       run: |
         cd build
         macdeployqt qlog.app
         cp /usr/local/lib/libhamlib.dylib qlog.app/Contents/Frameworks/libhamlib.dylib
         cp /usr/local/lib/libqt6keychain.dylib qlog.app/Contents/Frameworks/libqt6keychain.dylib
         install_name_tool -change /usr/local/lib/libhamlib.dylib @executable_path/../Frameworks/libhamlib.dylib qlog.app/Contents/MacOS/qlog
         install_name_tool -change /usr/local/lib/libqt6keychain.dylib @executable_path/../Frameworks/libqt6keychain.dylib qlog.app/Contents/MacOS/qlog
         otool -L qlog.app/Contents/MacOS/qlog
         macdeployqt qlog.app -dmg
     - name: Copy artifact
       uses: actions/upload-artifact@v3
       with:
         name: qlog
         path: /Users/runner/work/QLog/QLog/build/qlog.dmg

